# Running the parameter estimation
there are 5 examples 
## Eg. 1 Brownin Motion
We start with a very simple example,
\begin{align*}
    dx_{t}=\mu_S dt+\sigma_S dB_{t}
\end{align*}
where $\mu_S$ and $\sigma_S$ are the unknown parameter of our interest.
The SDE has an analytical solution $x(t) =\mu_S t +\sigma_S B_t $. 
Now assume that the GP has the form $X_t\sim \text{GP} (\mu_G t,\sigma_G^2 \mathcal{K}(t,t'))$. 
Thus, the goal is to minimize the function \eqref{eq:loss_fun}, where $\mu_{1i} =  \mu_G t_i + \mathcal{K}(t_i,t_{i-1})\mathcal{K}(t_{i-1},t_{i-1})^{-1}(y_{i-1}-\mu_G t_{i-1})$, $\sigma_{1i} =  \sigma_G (1 - \mathcal{K}(t_i,t_{i-1})\mathcal{K}(t_{i-1},t_{i-1})^{-1}\mathcal{K}(t_{i-1},t_i))$, $\mu_{2i} = x_{i-1}+ \mu_S \Delta t$, $\sigma_{2i}= \sigma_S\sqrt{\Delta t}$, 
where $\Delta t = (t_i-t_{i-1})$. 
We select the true values for the parameters $(\mu,\sigma)$ are $(2,0.4)$. 
The data is collected from the set $\bm{I} = \{0,0.01,0.02,\dotsm,1\}$. 

## Eg. 2 Ornstein–Uhlenbeck Process
The Ornstein–Uhlenbeck process $x_{t}$ is defined by the following stochastic differential equation:

\begin{equation}
   dx_{t}=\theta_S (\mu - x_{t}dt)+\sigma_S dB_{t}
\end{equation}
where $\mu_S >0$ and $\sigma_S >0$ are parameters and $B_{t}$ denotes the Wiener process.
Let's assume that the true value for the parameter is $\mu =1, \sigma = 0.4$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $S_0 = 1$. 
In this example, the mean function for GP is $\mu_G = S_0 \exp(\mu t)$, the variance function is $\sigma_G$, i.e., a constant parameter. 

## Eg. 3 Bessel Process
The Bessel process is given by the following form, 
\begin{equation}
    dx_t = \frac{\mu_S}{x_t} dt + \sigma_S d B_t.
\end{equation}
where $\mu_S >0$ and $\sigma_S >0$ are parameters and $B_{t}$ denotes the Wiener process.
Let's assume that the true value for the parameter is $\mu =5, \sigma = 0.5$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $x_0 = 1$. 
In this example, the mean function for GP is $\mu_G = (2\mu t + 1)^{1/2}$, the variance function is $\sigma_G$, i.e., a constant parameter. 


## Eg. 4 Geometric Brownian Motion
Another example is the geometric Brownian motion, which is given by 
\begin{align*}
    dx_{t}=\mu_S x_{t}dt+\sigma_S x_{t}dB_{t}
\end{align*}
where $\mu$ and $\sigma$ are the unknown parameter of our interest.
This purpose of this example is to demonstrate the use of non-stationary GP model. 
Let's assume that the true value for the parameter is $\mu =2, \sigma = 0.2$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $S_0 = 1$. 

In this example, the mean function for GP is $\mu_G = S_0 \exp(\mu t)$, the variance function is $\sigma_G = \sigma * \mu_G $. 


## Eg. 5 GARCH Model
Another example is the GARCH, which is given by 
\begin{align*}
    dx_{t}=\theta_1(\theta_2 - x_{t})dt+\sigma_S x_{t}dB_{t}
\end{align*}
This purpose of this example is to demonstrate the use of non-stationary GP model. 
Let's assume that the true value for the parameter is $(1,2,0.2)$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $x_0 = 1$. 

In this example, the mean function for GP is $\mu_G = \theta_2' - (\theta_2'-x_0)\exp(-\theta_1' t)$, the variance function is $\sigma_G = \sigma * \mu_G $. 

## Eg. 6 Continuous Time GARCH Model
Another example is the Continuous Time GARCH, which is given by 
\begin{align*}
dw_t & = \sqrt{x_t} d B^{1}_t \\
dx_{t} & = \theta_1(\theta_2 - x_{t})dt+\sigma_S x_{t}dB^2_{t}
\end{align*}
This purpose of this example is to demonstrate the use of non-stationary GP model. 
Let's assume that the true value for the parameter is $(1,2,0.2)$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $x_0 = 1$. 

In this example, the mean function for GP is $\mu_G = \theta_2' - (\theta_2'-x_0)\exp(-\theta_1' t)$, the variance function is $\sigma_G = \sigma * \mu_G $. 


## How to run these simulations:
Set operator: 
- operator = 0 : eg 1
- operator = 2 : eg 2
- operator = 3 : eg 3
- operator = -1 : eg 4
- operator = -2 : eg 5
- operator = -3 : eg 6

In [1]:

import numpy as np
from scripts import SIGMA # inferred module
from scripts import SDE_Model # inferred module
import torch
#import mkl
#mkl.set_num_threads(1)
import os

torch.set_num_threads(1)
operator = 0
sigma_e=0.0000000001
SDE=SDE_Model.SDE_Module(
    sde_operator = operator,
    sigma_e = sigma_e,
    n_I = 100,
    n_obs = 50,
    noisy_known = True,
    optimize_alg = False,
    band_width = 1.
    )

SIGMA_o= SIGMA.SIGMA(SDE, para = False ,rho= 1.) # call inference class

#res_margin = SIGMA_o.map_margin(nEpoch = 3000, opt_algorithm = 2)
res = SIGMA_o.map(nEpoch = 3000, opt_algorithm = 2)
res_hmc = SIGMA_o.Sample_Using_HMC(
        n_epoch = 500, 
        lsteps=100, 
        epsilon=1e-4, 
        n_samples=2000, 
        opt_algorithm = 2
        )
#magi2= test_script.MAGI_SDE_Infer(PDEmodel, KL=False) # call inference class
#res2 = magi2.map(nEpoch = 3000, opt_algorithm = 2)


GP_var tensor(1.0000e-11) Noise_var tensor(1.0000e-20) GP_parameter [1.] Standardized [1.]
Time for training GP: 0  secs
MLE: [1.67011752 0.37612496] MLE_analytical [1.67011752 0.37612496] True: tensor([2.0000, 0.4000])
start optimiza theta and u:
500 / 3000 current opt: theta: [1.68762109 0.71504231] [0.50921938] error/out_scale tensor([1.0000e-09])
1000 / 3000 current opt: theta: [1.71246308 0.71543762] [0.50839102] error/out_scale tensor([1.0000e-09])
1500 / 3000 current opt: theta: [1.74045704 0.71552002] [0.50844982] error/out_scale tensor([1.0000e-09])
2000 / 3000 current opt: theta: [1.76948664 0.71562425] [0.50852401] error/out_scale tensor([1.0000e-09])
2500 / 3000 current opt: theta: [1.79745011 0.71575493] [0.50861698] error/out_scale tensor([1.0000e-09])
3000 / 3000 current opt: theta: [1.82240625 0.71591828] [0.50873316] error/out_scale tensor([1.0000e-09])
Estimated parameter: [1.82240625 0.71591828] True parameter: [2.  0.4] Error of theta: tensor(0.2563) relative err te

/Users/lizhaohui/Nutstore Files/我的坚果云/Current_Work/SIGMA/github/SIGMA/scripts/HMC.py:46: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t5=torch.tensor(torch.ones(0))


tensor([1.6877, 0.7150])
tensor([1.6989, 0.7414])
tensor([1.6989, 0.7414])
tensor([1.7001, 0.7616])
tensor([1.7035, 0.7710])
tensor([1.7273, 0.7981])
tensor([1.7224, 0.8044])
tensor([1.7212, 0.8238])
tensor([1.7052, 0.8330])
tensor([1.7051, 0.8462])
tensor([1.7104, 0.8281])
tensor([1.7118, 0.8664])
tensor([1.7226, 0.9019])
tensor([1.7226, 0.9019])
tensor([1.7112, 0.9042])
tensor([1.6840, 0.9293])
tensor([1.6526, 0.9525])
tensor([1.6904, 0.9749])
tensor([1.6880, 0.9728])
tensor([1.7049, 0.9791])
tensor([1.7031, 0.9890])
tensor([1.7051, 0.9856])
tensor([1.7010, 1.0223])
tensor([1.7002, 1.0299])
tensor([1.7123, 1.0474])
tensor([1.7372, 1.0216])
tensor([1.7571, 1.0328])
tensor([1.7676, 1.0255])
tensor([1.7666, 1.0138])
tensor([1.7724, 1.0387])
tensor([1.7571, 1.0352])
tensor([1.7571, 1.0352])
tensor([1.7445, 1.0211])
tensor([1.7065, 1.0365])
tensor([1.6906, 1.0627])
tensor([1.6842, 1.0383])
tensor([1.6808, 1.0321])
tensor([1.6745, 1.0151])
tensor([1.6863, 1.0024])
tensor([1.6714, 0.9945])


In [3]:
import traceback
import numpy as np
from scripts import SIGMA # inferred module
from scripts import SDE_Model # inferred module
from scipy.io import savemat
import argparse
from concurrent.futures import ProcessPoolExecutor, wait
import torch
import mkl
mkl.set_num_threads(1)
torch.set_num_threads(1)


sigma_e = 0.000000001
SDE=SDE_Model.SDE_Module(
    sde_operator = 0,
    sigma_e = sigma_e,
    n_I = 100,
    n_obs = 20,
    noisy_known = True,
    optimize_alg = False,
    band_width = 1.
    )

SIGMA_o= SIGMA.SIGMA(SDE, para = False ,rho= 1.) # call inference class
#MAP_margin = SIGMA_o.map_margin(nEpoch = 3000, opt_algorithm = 2, center_modify = False)
#MAP_margin_c = SIGMA_o.map_margin(nEpoch = 3000, opt_algorithm = 2, center_modify = True)
MAP = SIGMA_o.map(nEpoch = 3000, opt_algorithm = 2, center_modify = False)
MAP_c = SIGMA_o.map(nEpoch = 3000, opt_algorithm = 2, center_modify = True)
MLE = SIGMA_o.mle_joint(nEpoch = 3000, opt_algorithm = 2)
res_hmc_lkh = SIGMA_o.HMC_lkh(
        n_epoch = 500, 
        lsteps=200, 
        epsilon=5e-5, 
        n_samples=2000, 
        opt_algorithm = 2
        )
sample = res_hmc_lkh['samples']
res_hmc_c,map = SIGMA_o.Sample_Using_HMC(
        n_epoch = 500, 
        lsteps=100, 
        epsilon=1e-4, 
        n_samples=2000, 
        opt_algorithm = 2,
        center_modify = True
        )
sample_post_c = res_hmc_c['samples']
res_hmc,map = SIGMA_o.Sample_Using_HMC(
        n_epoch = 500, 
        lsteps=100, 
        epsilon=1e-4, 
        n_samples=2000, 
        opt_algorithm = 2,
        center_modify = False
        )
sample_post = res_hmc['samples']
theta_mle = SIGMA_o.theta_MLE
theta_mle_a = SIGMA_o.theta_MLE_a
# SIGMA_p= SIGMA.SIGMA(SDE, para = True ,rho= 1.) # call inference class
# res_margin = SIGMA_p.map_margin(nEpoch = 3000, opt_algorithm = 2)
# res = SIGMA_p.map(nEpoch = 3000, opt_algorithm = 2)


filename =  'res/' + 'mcmc_source' + str(args.operator) + 'inst' + str(args.inst_num) + 'nobs' + str(args.n_obs) + 'n_I'+ str(args.n_I) + 'mcmc.mat'
ERR_summary = {
    'sample_lkh':sample,
    'sample_post':sample_post,
    'sample_post_c':sample_post_c,
    'theta_true': SDE.theta_true.numpy(),
    'theta_MLE': theta_mle,
    'theta_MLE_a':theta_mle_a,
    'theta_MLE_joint': MLE['theta_mle'].numpy(),
    'theta_MAP':MAP['theta_MAP'].numpy(),
    'theta_MAP_margin' : MAP_margin['theta_MAP'].numpy(),
    'theta_MAP_c':MAP_c['theta_MAP'].numpy(),
    'theta_MAP_margin_c' : MAP_margin_c['theta_MAP'].numpy(),
}
savemat(filename,ERR_summary)

ModuleNotFoundError: No module named 'mkl'