# Running the parameter estimation
there are 5 examples 
## Eg. 1 Brownin Motion
We start with a very simple example,
\begin{align*}
    dx_{t}=\mu_S dt+\sigma_S dB_{t}
\end{align*}
where $\mu_S$ and $\sigma_S$ are the unknown parameter of our interest.
The SDE has an analytical solution $x(t) =\mu_S t +\sigma_S B_t $. 
Now assume that the GP has the form $X_t\sim \text{GP} (\mu_G t,\sigma_G^2 \mathcal{K}(t,t'))$. 
Thus, the goal is to minimize the function \eqref{eq:loss_fun}, where $\mu_{1i} =  \mu_G t_i + \mathcal{K}(t_i,t_{i-1})\mathcal{K}(t_{i-1},t_{i-1})^{-1}(y_{i-1}-\mu_G t_{i-1})$, $\sigma_{1i} =  \sigma_G (1 - \mathcal{K}(t_i,t_{i-1})\mathcal{K}(t_{i-1},t_{i-1})^{-1}\mathcal{K}(t_{i-1},t_i))$, $\mu_{2i} = x_{i-1}+ \mu_S \Delta t$, $\sigma_{2i}= \sigma_S\sqrt{\Delta t}$, 
where $\Delta t = (t_i-t_{i-1})$. 
We select the true values for the parameters $(\mu,\sigma)$ are $(2,0.4)$. 
The data is collected from the set $\bm{I} = \{0,0.01,0.02,\dotsm,1\}$. 

## Eg. 2 Ornstein–Uhlenbeck Process
The Ornstein–Uhlenbeck process $x_{t}$ is defined by the following stochastic differential equation:

\begin{equation}
   dx_{t}=\theta_S (\mu - x_{t}dt)+\sigma_S dB_{t}
\end{equation}
where $\mu_S >0$ and $\sigma_S >0$ are parameters and $B_{t}$ denotes the Wiener process.
Let's assume that the true value for the parameter is $\mu =1, \sigma = 0.4$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $S_0 = 1$. 
In this example, the mean function for GP is $\mu_G = S_0 \exp(\mu t)$, the variance function is $\sigma_G$, i.e., a constant parameter. 

## Eg. 3 Bessel Process
The Bessel process is given by the following form, 
\begin{equation}
    dx_t = \frac{\mu_S}{x_t} dt + \sigma_S d B_t.
\end{equation}
where $\mu_S >0$ and $\sigma_S >0$ are parameters and $B_{t}$ denotes the Wiener process.
Let's assume that the true value for the parameter is $\mu =5, \sigma = 0.5$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $x_0 = 1$. 
In this example, the mean function for GP is $\mu_G = (2\mu t + 1)^{1/2}$, the variance function is $\sigma_G$, i.e., a constant parameter. 


## Eg. 4 Geometric Brownian Motion
Another example is the geometric Brownian motion, which is given by 
\begin{align*}
    dx_{t}=\mu_S x_{t}dt+\sigma_S x_{t}dB_{t}
\end{align*}
where $\mu$ and $\sigma$ are the unknown parameter of our interest.
This purpose of this example is to demonstrate the use of non-stationary GP model. 
Let's assume that the true value for the parameter is $\mu =2, \sigma = 0.2$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $S_0 = 1$. 

In this example, the mean function for GP is $\mu_G = S_0 \exp(\mu t)$, the variance function is $\sigma_G = \sigma * \mu_G $. 


## Eg. 5 GARCH Model
Another example is the GARCH, which is given by 
\begin{align*}
    dx_{t}=\theta_1(\theta_2 - x_{t})dt+\sigma_S x_{t}dB_{t}
\end{align*}
This purpose of this example is to demonstrate the use of non-stationary GP model. 
Let's assume that the true value for the parameter is $(1,2,0.2)$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $x_0 = 1$. 

In this example, the mean function for GP is $\mu_G = \theta_2' - (\theta_2'-x_0)\exp(-\theta_1' t)$, the variance function is $\sigma_G = \sigma * \mu_G $. 

## Eg. 6 Continuous Time GARCH Model
Another example is the Continuous Time GARCH, which is given by 
\begin{align*}
dw_t & = \sqrt{x_t} d B^{1}_t \\
dx_{t} & = \theta_1(\theta_2 - x_{t})dt+\sigma_S x_{t}dB^2_{t}
\end{align*}
This purpose of this example is to demonstrate the use of non-stationary GP model. 
Let's assume that the true value for the parameter is $(1,2,0.2)$. 
The data is observed on a set $\{t_i = i/100, i=0,1,2,\dots,100\}$.
The initial condition is given by $x_0 = 1$. 

In this example, the mean function for GP is $\mu_G = \theta_2' - (\theta_2'-x_0)\exp(-\theta_1' t)$, the variance function is $\sigma_G = \sigma * \mu_G $. 


## How to run these simulations:
Set operator: 
- operator = 0 : eg 1
- operator = 2 : eg 2
- operator = 3 : eg 3
- operator = -1 : eg 4
- operator = -2 : eg 5
- operator = -3 : eg 6

In [3]:

import numpy as np
from scripts import SIGMA # inferred module
from scripts import SDE_Model # inferred module
import torch
#import mkl
#mkl.set_num_threads(1)
import os

torch.set_num_threads(1)
operator = 0
sigma_e=0.0000000001
SDE=SDE_Model.SDE_Module(
    sde_operator = operator,
    sigma_e = sigma_e,
    n_I = 100,
    n_obs = 50,
    noisy_known = True,
    optimize_alg = False,
    band_width = 1.
    )

SIGMA_o= SIGMA.SIGMA(SDE, para = False ,rho= 1.) # call inference class

#res_margin = SIGMA_o.map_margin(nEpoch = 3000, opt_algorithm = 2)
res = SIGMA_o.map(nEpoch = 3000, opt_algorithm = 2)
res_hmc = SIGMA_o.Sample_Using_HMC(
        n_epoch = 500, 
        lsteps=100, 
        epsilon=1e-4, 
        n_samples=2000, 
        opt_algorithm = 2
        )
#magi2= test_script.MAGI_SDE_Infer(PDEmodel, KL=False) # call inference class
#res2 = magi2.map(nEpoch = 3000, opt_algorithm = 2)


GP_var tensor(1.0000e-11) Noise_var tensor(1.0000e-20) GP_parameter [1.] Standardized [1.]
Time for training GP: 0  secs
MLE: [2.62731634 0.4012586 ] MLE_analytical [2.62731634 0.4012586 ] True: tensor([2.0000, 0.4000])
start optimiza theta and u:
500 / 3000 current opt: theta: [2.5770586  0.73740319] [0.52459603] error/out_scale tensor([1.0000e-09])
1000 / 3000 current opt: theta: [2.54433286 0.73768597] [0.52419851] error/out_scale tensor([1.0000e-09])
1500 / 3000 current opt: theta: [2.51099332 0.73781906] [0.52429318] error/out_scale tensor([1.0000e-09])
2000 / 3000 current opt: theta: [2.48420259 0.73798974] [0.52441456] error/out_scale tensor([1.0000e-09])
2500 / 3000 current opt: theta: [2.46622638 0.73820574] [0.52456813] error/out_scale tensor([1.0000e-09])
3000 / 3000 current opt: theta: [2.4566851  0.73847767] [0.52476146] error/out_scale tensor([1.0000e-09])
Estimated parameter: [2.4566851  0.73847767] True parameter: [2.  0.4] Error of theta: tensor(0.4020) relative err te

/Users/lizhaohui/Nutstore Files/我的坚果云/Current_Work/SIGMA/CODE/SIGMA/scripts/HMC.py:46: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t5=torch.tensor(torch.ones(0))


tensor([2.5977, 0.7690])
tensor([2.5973, 0.8202])
tensor([2.6011, 0.8546])
tensor([2.6012, 0.8820])
tensor([2.5952, 0.9253])
tensor([2.5817, 0.9021])
tensor([2.5894, 0.9387])
tensor([2.5929, 0.9487])
tensor([2.6054, 0.9559])
tensor([2.6096, 0.9411])
tensor([2.6076, 0.9483])
tensor([2.6043, 0.9383])
tensor([2.6116, 0.9401])
tensor([2.6050, 0.9289])
tensor([2.6074, 0.9508])
tensor([2.5900, 0.9516])
tensor([2.5818, 0.9853])
tensor([2.5706, 0.9885])
tensor([2.5628, 1.0228])
tensor([2.5586, 1.0214])
tensor([2.5264, 1.0191])
tensor([2.5341, 1.0175])
tensor([2.5417, 1.0015])
tensor([2.5779, 1.0038])
tensor([2.5623, 1.0204])
tensor([2.5595, 1.0121])
tensor([2.5659, 1.0133])
tensor([2.5429, 1.0562])
tensor([2.5403, 1.0611])
tensor([2.5710, 1.0556])
tensor([2.5898, 1.0710])
tensor([2.6152, 1.0663])
tensor([2.6152, 1.0663])
tensor([2.6118, 1.0681])
tensor([2.6238, 1.0775])
tensor([2.6222, 1.0645])
tensor([2.6325, 1.0545])
tensor([2.6342, 1.0144])
tensor([2.6051, 0.9922])
tensor([2.5818, 0.9900])


In [3]:
import traceback
import numpy as np
from scripts import SIGMA # inferred module
from scripts import SDE_Model # inferred module
from scipy.io import savemat
import argparse
from concurrent.futures import ProcessPoolExecutor, wait
import torch
import mkl
mkl.set_num_threads(1)
torch.set_num_threads(1)


sigma_e = 0.000000001
SDE=SDE_Model.SDE_Module(
    sde_operator = 0,
    sigma_e = sigma_e,
    n_I = 100,
    n_obs = 20,
    noisy_known = True,
    optimize_alg = False,
    band_width = 1.
    )

SIGMA_o= SIGMA.SIGMA(SDE, para = False ,rho= 1.) # call inference class
#MAP_margin = SIGMA_o.map_margin(nEpoch = 3000, opt_algorithm = 2, center_modify = False)
#MAP_margin_c = SIGMA_o.map_margin(nEpoch = 3000, opt_algorithm = 2, center_modify = True)
MAP = SIGMA_o.map(nEpoch = 3000, opt_algorithm = 2, center_modify = False)
MAP_c = SIGMA_o.map(nEpoch = 3000, opt_algorithm = 2, center_modify = True)
MLE = SIGMA_o.mle_joint(nEpoch = 3000, opt_algorithm = 2)
res_hmc_lkh = SIGMA_o.HMC_lkh(
        n_epoch = 500, 
        lsteps=200, 
        epsilon=5e-5, 
        n_samples=2000, 
        opt_algorithm = 2
        )
sample = res_hmc_lkh['samples']
res_hmc_c,map = SIGMA_o.Sample_Using_HMC(
        n_epoch = 500, 
        lsteps=100, 
        epsilon=1e-4, 
        n_samples=2000, 
        opt_algorithm = 2,
        center_modify = True
        )
sample_post_c = res_hmc_c['samples']
res_hmc,map = SIGMA_o.Sample_Using_HMC(
        n_epoch = 500, 
        lsteps=100, 
        epsilon=1e-4, 
        n_samples=2000, 
        opt_algorithm = 2,
        center_modify = False
        )
sample_post = res_hmc['samples']
theta_mle = SIGMA_o.theta_MLE
theta_mle_a = SIGMA_o.theta_MLE_a
# SIGMA_p= SIGMA.SIGMA(SDE, para = True ,rho= 1.) # call inference class
# res_margin = SIGMA_p.map_margin(nEpoch = 3000, opt_algorithm = 2)
# res = SIGMA_p.map(nEpoch = 3000, opt_algorithm = 2)


filename =  'res/' + 'mcmc_source' + str(args.operator) + 'inst' + str(args.inst_num) + 'nobs' + str(args.n_obs) + 'n_I'+ str(args.n_I) + 'mcmc.mat'
ERR_summary = {
    'sample_lkh':sample,
    'sample_post':sample_post,
    'sample_post_c':sample_post_c,
    'theta_true': SDE.theta_true.numpy(),
    'theta_MLE': theta_mle,
    'theta_MLE_a':theta_mle_a,
    'theta_MLE_joint': MLE['theta_mle'].numpy(),
    'theta_MAP':MAP['theta_MAP'].numpy(),
    'theta_MAP_margin' : MAP_margin['theta_MAP'].numpy(),
    'theta_MAP_c':MAP_c['theta_MAP'].numpy(),
    'theta_MAP_margin_c' : MAP_margin_c['theta_MAP'].numpy(),
}
savemat(filename,ERR_summary)

ModuleNotFoundError: No module named 'mkl'